name: embedded_system
version: 1.0.0+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies:

  #Firebase
  firebase_core:
  firebase_auth:
  firebase_analytics:
  cloud_firestore:
  firebase_database:
  firebase_storage:
  firebase_crashlytics:
  firebase_ui_firestore:
  firebase_messaging:

  flutter_local_notifications:
  url_strategy:

  http:

  auto_route:
  bloc:
  flutter_bloc:
  get_it:
  injectable:
  json_annotation:
  freezed_annotation:
  equatable:
  dartz:

  shared_preferences:
  validadores:
  cupertino_icons: ^1.0.2
  google_fonts:
  flutter_screenutil:
  font_awesome_flutter: ^10.4.0
  syncfusion_flutter_charts: ^20.3.47
  intl:
  rounded_loading_button:
  flutter_speed_dial:

  flutter: 
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:

  flutter_launcher_icons:
  flutter_native_splash:
  change_app_package_name:

  auto_route_generator:
  build_runner:
  freezed:
  injectable_generator:
  json_serializable: ^6.6.2

  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_icons:
  image_path: "images/icon.jpeg"
  adaptive_icon_background: '#4caf50'
  adaptive_icon_foreground: "images/icon.jpeg"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "images/icon.jpeg"
    background_color: "#4caf50"
    theme_color: "#4caf50"
  windows:
    generate: true
    image_path: "images/icon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/icon.jpeg"

flutter_native_splash:
  color: "#ffffff"
  image: "images/icon.jpeg"
  android: true
  ios: true

flutter: 
  uses-material-design: true

