name: embedded_system
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: any
  flutter_screenutil: any
  http: any
  equatable: any
  dartz: any
  get: 4.6.5
  multicast_dns:
  font_awesome_flutter: ^10.4.0
  syncfusion_flutter_charts:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

