// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNGVGMxuyXW-LxhosVBr72xpBLq1AHcgQ',
    appId: '1:330379483771:web:36751445fdfda2e276a0de',
    messagingSenderId: '330379483771',
    projectId: 'granja-dd887',
    authDomain: 'granja-dd887.firebaseapp.com',
    databaseURL: 'https://granja-dd887-default-rtdb.firebaseio.com',
    storageBucket: 'granja-dd887.appspot.com',
    measurementId: 'G-9BS90L1GJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtw_EPjnCjP2PL5AJmFoEAOG2rMROTzb8',
    appId: '1:330379483771:android:8ebfb288023c7eb476a0de',
    messagingSenderId: '330379483771',
    projectId: 'granja-dd887',
    databaseURL: 'https://granja-dd887-default-rtdb.firebaseio.com',
    storageBucket: 'granja-dd887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB64s-hhDkIrpj732pgWWif3y6B6AVAm7U',
    appId: '1:330379483771:ios:0caefb1a1391b84676a0de',
    messagingSenderId: '330379483771',
    projectId: 'granja-dd887',
    databaseURL: 'https://granja-dd887-default-rtdb.firebaseio.com',
    storageBucket: 'granja-dd887.appspot.com',
    iosBundleId: 'com.example.embeddedSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB64s-hhDkIrpj732pgWWif3y6B6AVAm7U',
    appId: '1:330379483771:ios:0caefb1a1391b84676a0de',
    messagingSenderId: '330379483771',
    projectId: 'granja-dd887',
    databaseURL: 'https://granja-dd887-default-rtdb.firebaseio.com',
    storageBucket: 'granja-dd887.appspot.com',
    iosBundleId: 'com.example.embeddedSystem',
  );
}
